import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { CECreditSummary } from './report-types';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica' },
  header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { marginBottom: 15 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { fontSize: 10, color: '#666', width: '40%' },
  value: { fontSize: 10, fontWeight: 'bold', width: '60%', textAlign: 'right' },
  table: { marginTop: 10, border: '1px solid #ccc' },
  tableHeader: { backgroundColor: '#f0f0f0', padding: 5, fontSize: 10, fontWeight: 'bold' },
  tableRow: { padding: 5, fontSize: 9, borderBottom: '1px solid #eee' },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, fontSize: 8, color: '#999', textAlign: 'center' },
  statusReady: { color: '#22c55e', fontWeight: 'bold' },
  statusWarning: { color: '#eab308', fontWeight: 'bold' },
  statusDanger: { color: '#ef4444', fontWeight: 'bold' },
});

/**
 * Generates a PDF report for a user's license and CE credit status.
 * @param summary - The data containing license info, CE credits, and readiness score.
 * @returns A Blob containing the PDF file.
 */
export async function generateLicenseReportPDF(summary: CECreditSummary): Promise<Blob> {
  const ReportDocument = () => (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text>RenewPilot License Compliance Report</Text>
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 14, marginBottom: 10, fontWeight: 'bold' }}>License Overview</Text>
          <View style={styles.row}>
            <Text style={styles.label}>License Type:</Text>
            <Text style={styles.value}>{summary.licenseType}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>State:</Text>
            <Text style={styles.value}>{summary.state}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>License Number:</Text>
            <Text style={styles.value}>{summary.licenseNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Renewal Date:</Text>
            <Text style={styles.value}>{new Date(summary.renewalDate).toLocaleDateString()}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 14, marginBottom: 10, fontWeight: 'bold' }}>Readiness Status</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Readiness Score:</Text>
            <Text style={[styles.value, getScoreStyle(summary.readinessScore)]}>
              {summary.readinessScore}%
            </Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Required Hours:</Text>
            <Text style={styles.value}>{summary.requiredHours}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Completed Hours:</Text>
            <Text style={styles.value}>{summary.completedHours}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Remaining Hours:</Text>
            <Text style={styles.value}>{summary.requiredHours - summary.completedHours}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={{ fontSize: 14, marginBottom: 5, fontWeight: 'bold' }}>CE Credit History</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={{ width: '40%' }}>Title</Text>
              <Text style={{ width: '30%' }}>Date</Text>
              <Text style={{ width: '30%', textAlign: 'right' }}>Hours</Text>
            </View>
            {summary.ceCredits.map((credit, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={{ width: '40%' }}>{credit.title}</Text>
                <Text style={{ width: '30%' }}>{new Date(credit.date).toLocaleDateString()}</Text>
                <Text style={{ width: '30%', textAlign: 'right' }}>{credit.hours}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.footer}>
          <Text>Generated by RenewPilot on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}</Text>
          <Text>This is an unofficial record. Please verify with your state board.</Text>
        </View>
      </Page>
    </Document>
  );

  const blob = await pdf(<ReportDocument />).toBlob();
  return blob;
}

/**
 * Helper to determine text color based on readiness score.
 */
function getScoreStyle(score: number): any {
  if (score >= 90) return styles.statusReady;
  if (score >= 50) return styles.statusWarning;
  return styles.statusDanger;
}
